### ISSUE TITLE
Nighttime Forecast

### ISSUE THREAD

**Issue by Psukeo** [vbguyny/ws4kp#1]
Instead of only showing Today or Tomorrow's Forecast only, use the nighttime forecast as well.

EXAMPLE:
If Today's forecast is available, show Tonight's forecast 2nd.
If Tomorrow's forecast is available, show Tonight's forecast 1st.

**Comment by vbguyny** [comment]
This is a test

**Comment by Psukeo** [comment]
Any progress on the nighttime forecast? Just checking.

**Comment by vbguyny** [comment]
It looks like the issue is I am missing too many night time images.  The ones that you provided where great but I am missing ones such as night time windy.

**Comment by malekmasoud** [comment]
I know the original WeatherSTAR 4000 didn't have the nighttime forecast during the 90's, but here are three nighttime icons that I have created for you:

1. Scattered (Rain) Showers Night
![scattered-showers-night](https://cloud.githubusercontent.com/assets/25880200/23102366/f897baa6-f675-11e6-9028-65373e479f4f.gif)

2. Scattered Snow Showers Night
![scattered-snow-showers-night](https://cloud.githubusercontent.com/assets/25880200/23102367/f8a977fa-f675-11e6-8ada-5cf15277a1bd.gif)

3. Scattered Thunderstorms Night
![scattered-tstorms-night](https://cloud.githubusercontent.com/assets/25880200/23102369/fd7751f8-f675-11e6-9e46-cc3c7e4e2134.gif)

Oh, and as for the nighttime windy icon?
![windy-night](https://cloud.githubusercontent.com/assets/25880200/23102411/b8cfe244-f676-11e6-87dc-955d57bc4c53.gif)

**Comment by Psukeo** [comment]
Holy crap, these are amazing! I made some that were similar to the daytime ones, but these are a lot more pleasing.

**Comment by vbguyny** [comment]
@malekmasoud: Thanks!  I'll be sure to incorporate theses images into a future version of the site!

**Comment by vbguyny** [comment]
FYI, this is what I have so far.  I am still working on it so stay tuned!
![ws4kp18](https://cloud.githubusercontent.com/assets/871502/23105199/0c172e76-f6a9-11e6-8c46-18b4f2e83a43.png)

**Comment by Psukeo** [comment]
@vbguyny Nice! Hope it gets released in the next 2 or 3 days!

**Comment by vbguyny** [comment]
This has been implemented in v1.31 which is now live.

**Comment by Psukeo** [comment]
Alright. Thank you for helping! I have another suggestion I'll open soon since I have a soure that might work.

**Comment by vbguyny** [comment]
@malekmasoud: I would like to give you credit for the images on the front page for the graphics.  Should I use your handle or your real name?

**Comment by malekmasoud** [comment]
@vbguyny Both my handle and real name.
