### ISSUE TITLE
Image and Full Screen Problem.

### ISSUE THREAD

**Issue by itsRoly4266** [vbguyny/ws4kp#10]
I wonder if there'll be a feature in the future where you can put your own image on the corner to replace the WeatherStar 4000+ logo.

I say that because I think that businesses and even apartment complexes can benefit from this service just by having their own logo seen on the service as well as offering their own scrolling text at the bottom, which by the way, is a very helpful thing too.

Plus, when I put it in full screen, the screen gets smaller, while still in full screen, after a little while. Will that be fixed too?

**Comment by vbguyny** [comment]
Hello @itsRoly4266!

Regarding your first question, if you want you can download the source code and make modifications for a custom logo by replacing the logo files in the image folder.

As far as the screen getting smaller, could you please describe the issue in greater detail?  For example, what type of computer or device you are running and which browser.  Please include screen shots as well as which location(s) you querying.

Thanks,
-Mike

**Comment by twostrikesteal** [comment]
I Have the same problem.  When it goes to the forecast for the day map and forecast for that night map it shrinks the image into the top left corner in full screen.  This happens on my computers running google chrome browser.  
![fireshot capture 5 - weatherstar 4000 ver1 - https___battaglia ddns net_twc_twc2 html](https://user-images.githubusercontent.com/45848949/49937599-d8c5e000-fe9c-11e8-9160-f1da809a65c6.png)

**Comment by vbguyny** [comment]
Hello @twostrikesteal, are you able to get the issue to happen every time?  I am using Chrome on my Windows 10 PC and not able to duplicate the issue.

**Comment by twostrikesteal** [comment]
Yes every time.  I'm running chrome on Windows 7.  I'm also running the
same on my work desktop and it does the same thing.  It only happens on
those two frames.

Mr. Ryan P. Desselle
600 W Lewis St. #4
Calmar, IA 52132
PH# 563-387-7153

**Comment by vbguyny** [comment]
Hello @twostrikesteal thanks for the additional information. I tested on my spare PC running Windows 7 and the Chrome 71 and still not able to duplicate.  Some additional questions for how you get this issue to happen: 

- Are you running in full screen? 
- Is the site in "Play Mode" (in other words, the screens switch automatically)?
- If not, how are you switching screens (swiping, using the left/right keys, pressing the left/right buttons on the page)?

Thanks!

**Comment by twostrikesteal** [comment]
Yes this is only in full screen mode.  In automatic mode and single screen
switching mode.

**Comment by twostrikesteal** [comment]
![screenshot_20181214-183325_chrome](https://user-images.githubusercontent.com/45848949/50036492-d82d6680-ffce-11e8-9e83-a00387253706.jpg)

**Comment by twostrikesteal** [comment]
![screenshot_20181214-183320_chrome](https://user-images.githubusercontent.com/45848949/50036502-e9767300-ffce-11e8-9438-f978d144c140.jpg)

**Comment by twostrikesteal** [comment]
![screenshot_20181214-183333_chrome](https://user-images.githubusercontent.com/45848949/50036508-f09d8100-ffce-11e8-8407-d27563e4bc74.jpg)

**Comment by twostrikesteal** [comment]
First two screenshots are as I said from my s7.  Last is the next screen as it should be displayed, and as are all the other screens besides those two.

**Comment by vbguyny** [comment]
@twostrikesteal thanks for the information, this is great! One more question, what is you the resolution of your desktop?

**Comment by twostrikesteal** [comment]
1360 X 768

**Comment by vbguyny** [comment]
Hello @twostrikesteal I have ruled out a lot of possible issues however I am still not able to duplicate/figure out the issue.  Could you see if there are any JavaScript errors in your Chrome browser?  The next time you are able to duplicate the issue in Chrome, press F12 and please copy and paste the errors here.

**Comment by vbguyny** [comment]
I believed I solved these issues in the latest update.
