### ISSUE TITLE
video will not play

### ISSUE THREAD

**Issue by Fealmar1** [vbguyny/ws4kp#100]
The video is just a black screen, all the buttons are not doing anything. idk what is going on, someone pls help me here! idk how to set labels, so... Help Wanted!

**Comment by vbguyny** [comment]
@Fealmar1 the site is working for me. Could you please check again? If the issue persists, please indicate which location that you entered in the search field.

**Comment by Fealmar1** [comment]
> @Fealmar1 the site is working for me. Could you please check again? If the issue persists, please indicate which location that you entered in the search field.

Oklahoma City and even Oklahoma City (Oklahoma County) it's still not working

**Comment by vbguyny** [comment]
They are working for me:
![image](https://github.com/vbguyny/ws4kp/assets/871502/bc6b0636-0c43-45da-afa7-3bc6112e4126)
![image](https://github.com/vbguyny/ws4kp/assets/871502/c2fe2d36-0d20-4c6b-820e-d8778e60e077)
Could you indicate what device, operating system, and browser that you are using?

**Comment by Fealmar1** [comment]
> They are working for me: ![image](https://user-images.githubusercontent.com/871502/260343623-bc6b0636-0c43-45da-afa7-3bc6112e4126.png) ![image](https://user-images.githubusercontent.com/871502/260343705-c2fe2d36-0d20-4c6b-820e-d8778e60e077.png) Could you indicate what device, operating system, and browser that you are using?

I am Currently using Google, and an HP Windows 11 Laptop with an Intel Core i3

**Comment by vbguyny** [comment]
That's strange considering that Edge uses the same browser engine as Chrome does under the hood.
Could you test with Chrome again but this time before going to the weather site, press F12 in Chrome and then go to the site. Please let me know if and what types of errors appear.

**Comment by Fealmar1** [comment]
i'm fine, i have a way to access and see the video on the site now and that's just fine by me!
