### ISSUE TITLE
1 issue / some suggestions

### ISSUE THREAD

**Issue by 10000002814823229** [vbguyny/ws4kp#102]
Hello, thank you so much for making this emulator. One issue (on mac) is sometimes the music stops but the video keeps going. Am I just reaching the end of the playlist when this happens?

suggestion 1: have a way to save favorite locations.

suggestion 2: is it possible to have a holiday music version like they used to have in December?

Also, is it possible to pull in international weather data and use it on this emulator?

Again thank you for making this. I love it.

**Comment by vbguyny** [comment]
@10000002814823229 

Thank you for your kind words, I'm glad that you enjoy it!

Yea, there is a bug somewhere in the JavaScript when the audio stops. I haven't had a chance to look at it.

As far as your suggestions:
1. There is no way to favorite locations in the site, however you can use bookmarks in your browser which contains the location in the query string. Example: https://battaglia.ddns.net/twc/?location=Medford,%20NY%20USA
2. Technically it is possible but I don't have any plans on doing this at the moment.
3. Unfortunately, the data from NOAA only includes that of the United States. I don't know what would be involved to get weather data from other countries. I would imagine that this would be a major undertaking.

-Mike

**Comment by vbguyny** [comment]
The issue with the music stopping could be related to: https://github.com/vbguyny/ws4kp/issues/91
