### ISSUE TITLE
Minor text presentation issues on the "Current Conditions" page

### ISSUE THREAD

**Issue by bradtchapman** [vbguyny/ws4kp#104]
While checking weather for Big Bear City, CA, I noticed some minor issues with the text on the Current Conditions page, including misalignment and crowding / overlapping.

On the line for "Ceiling," when ceiling is unlimited, either Ceiling or Unlimited needs to be abbreviated.  Suggestions:  CEIL. or UNLIM. or UNLTD.
On the line for Visibility, the text is crowded / overlapping when the visibility is more than 10 miles but less than unlimited.
On the line for barometric pressure, the number needs to be right-aligned to the edge of the window — there's a gap after the last digit, and the barometric readings are usually expressed with two decimal places (##.## inHg).

See attached screenshot.  Thank you!

Details:
Location: Big Bear City, CA
Station Id: KL35
Radar Id: SGX
Zone Id: CAZ055

Browser: Safari 16.5
Operating System: macOS 13.4

<img width="1512" alt="Screenshot 2023-11-23 at 8 55 35 PM" src="https://github.com/vbguyny/ws4kp/assets/32527656/4f6b1e4e-01f5-4ee8-87c7-bda3de91ff2b">

**Comment by bradtchapman** [comment]
Browser: Safari 16.5, MacOS 13.4 (Ventura).

**Comment by bradtchapman** [comment]
Update: the text looks less cramped on Chrome, and the font weight is different, too.  

See attached screenshot.

<img width="656" alt="Screenshot 2023-11-24 at 1 14 25 AM" src="https://github.com/vbguyny/ws4kp/assets/32527656/e2d4a993-ed78-4a12-bc9d-cd703a074d56">

**Comment by bradtchapman** [comment]
Text weight on Firefox is consistent with Chrome, but spacing is a bit off.

<img width="639" alt="TWC-Current-Firefox" src="https://github.com/vbguyny/ws4kp/assets/32527656/7bf107f0-0f88-441c-ad60-949459629021">

**Comment by vbguyny** [comment]
This appears to be an issue with Safari how it renders fonts in a canvas. There are CSS hacks to get this working but they don't work for the canvas object.
Someone suggested that this can be fixed by adjusting "Font Smoothing" in the Mac settings: https://help.apple.com/pages/mac/4.3/help/English.lproj/pgs/sl15187853.html
