### ISSUE TITLE
In Safari, music does not auto-play or auto-advance, and always stops after 1-2 minutes.

### ISSUE THREAD

**Issue by bradtchapman** [vbguyny/ws4kp#106]
Hello,

On Safari 16.5, the music does not start automatically.  It starts muted.  Additionally, even if I do unmute it, the music stops after 1-2 minutes and I have to unmute to hear music again.

In Google Chrome, the site works as expected.

**Comment by vbguyny** [comment]
The issue with the music stopping is related to: https://github.com/vbguyny/ws4kp/issues/91
