### ISSUE TITLE
Barometric pressure trend arrow / symbol is missing on Chrome and Safari.  Only appears on Firefox.

### ISSUE THREAD

**Issue by bradtchapman** [vbguyny/ws4kp#107]
I just figured out why there is an odd space on the line with barometric pressure: a necessary symbol is not rendering.  In Firefox, I saw a trend arrow pointing downward.  This arrow is absent on Safari and Chrome.

If the pressure is steady, should there be a flat line?  Otherwise, a blank space looks strange.

See screenshots below from Firefox, Chrome, Safari (in that order):

<img width="639" alt="TWC-Current-Firefox" src="https://github.com/vbguyny/ws4kp/assets/32527656/4a8a7cba-f45e-44a4-b327-36c82ab3414a">

<img width="638" alt="TWC-Current-Chrome" src="https://github.com/vbguyny/ws4kp/assets/32527656/8006fbcb-b929-4620-9bd0-9668ef05d9e5">

<img width="630" alt="TWC-Current-Safari" src="https://github.com/vbguyny/ws4kp/assets/32527656/3f36bafe-2dfe-44e9-9c74-d7fbd6352e5d">

**Comment by vbguyny** [comment]
@bradtchapman there is no arrow if the pressure is steady. I see that the screenshots were taken at different times. Could you please verify that issue happens when an arrow is displayed in Chrome and it isn't there for the different browsers?
