### ISSUE TITLE
Alert: New API Impending.... 

### ISSUE THREAD

**Issue by thetechknight** [vbguyny/ws4kp#112]
Someone has alerted me that the weather.gov API and site will be changing soon. If you are using this API for weather data, you will need to adapt shortly. See here: 

https://github.com/weather-gov/weather.gov?tab=readme-ov-file

**Comment by vbguyny** [comment]
@thetechknight thanks for bringing this to my attention. However I don't see anything in that repo indicating that they are doing anything with the API part of the site. The repo appears to be focus strictly on the website itself.

Here is their milestones for this project:
https://github.com/weather-gov/weather.gov/blob/main/docs/product/MVP-roadmap.md
