### ISSUE TITLE
HTTP Error 500.0 - ASP.Net Core IIS hosting failure (in-process)

### ISSUE THREAD

**Issue by mikemaddenn** [vbguyny/ws4kp#114]
Hello; I'm trying to get this setup but after following the steps to install and navigating to http://localhost/ws4kp, I am receiving this error.

```
 HTTP Error 500.0 - ASP.NET Core IIS hosting failure (in-process)
Troubleshooting steps:

    Check the system event log for error messages
    Enable logging the application process' stdout messages
    Attach a debugger to the application process and inspect
```
![image](https://github.com/vbguyny/ws4kp/assets/63440314/72e686b1-31b5-42ef-9ced-6d420c8faea8)

I double checked that the correct .NET hosting bundle version is here and it looks right. Additionally, in Event Viewer I see two logs:
```
Failed to start application '/LM/W3SVC/1/ROOT/ws4kp', ErrorCode '0x8007023e'.

Application 'C:\ws4kp-master\' failed to start. Exception message:
Executable was not found at 'C:\ws4kp-master\bin\Debug\net8.0\ws4kp.exe' # note that this path doesn't exist
```

Any idea what I might be doing wrong? Thank you.

**Comment by vbguyny** [comment]
@mikemaddenn try downloading the files from https://github.com/vbguyny/ws4kp/tree/master/bin

**Comment by mikemaddenn** [comment]
@vbguyny Thanks for replying so quickly. Interestingly that did bring the site up, but I'm stuck with a black screen and no ability to select a city/zip.

Have you seen this issue before?

![image](https://github.com/vbguyny/ws4kp/assets/63440314/011b0057-9abf-46d6-8e23-ba02287619f0)

**Comment by vbguyny** [comment]
There might be an error in your browser. Could you bring up the console and let me know if you see any errors.

**Comment by mikemaddenn** [comment]
A few interesting things here. I receive the "Unable to unlock screen orientation" when just visiting the page, which is interesting because it's in the OnFullScreen method and I'm running this out of windowed mode.

As for the other errors, the GET failure to that geocode API comes up when trying to search a location, and the last typeerror occurs when clicking any buttons (play, menu, etc.). Thanks for the help troubleshooting.

![image](https://github.com/vbguyny/ws4kp/assets/63440314/96951f04-0de3-4f3e-8131-53a6852fc3ef)

**Comment by vbguyny** [comment]
It appears to be similar to the issue described in https://github.com/vbguyny/ws4kp/issues/82
Take a look at the thread and try the solution on your end.

**Comment by mikemaddenn** [comment]
Yep, this fixed it. Thanks again for the help. Awesome emulator

**Comment by vbguyny** [comment]
You are very welcome 😁
