### ISSUE TITLE
Stuck Loading - Errors 

### ISSUE THREAD

**Issue by K-A-0-S** [vbguyny/ws4kp#116]
There are some errors that are preventing the emulator from loading completely.

![image](https://github.com/vbguyny/ws4kp/assets/169946395/aabe5ba3-2be9-494d-8565-8622b86f49c5)

This address produces an error...

u: https://api.weather.com/v3/location/near?apiKey=21d8a80b3d6b444998a80b3d6b1449d3&geocode=25.7751%2C-80.1947&product=airport&subproduct=major&format=json

![image](https://github.com/vbguyny/ws4kp/assets/169946395/33e6919e-e3bc-4343-9096-cce5a601f798)

Seems something may have changed. API? I am having issues with OTHER emulators as well.

![image](https://github.com/vbguyny/ws4kp/assets/169946395/b479eb98-a1ca-4155-b363-8e91bcabaeb3)

EDIT: I think it may be the API Key?

EDIT 2: Replacing the key fixed the issue for me.

Fixed...

![image](https://github.com/vbguyny/ws4kp/assets/169946395/aa08fcb3-a52a-4331-99c9-0185947dd835)

**Comment by K-A-0-S** [comment]
I also wanted to say what a great job you have done with this emulator. Thanks for your hard work.

**Comment by K-A-0-S** [comment]
I use this like a widget on my desktop...

![image](https://github.com/vbguyny/ws4kp/assets/169946395/1d9f2f5d-de92-431d-9c98-17201bd901a1)

I have installed the IIS server and use ssh port forwarding to serve the other deices on LAN. Works Great! 

Again, thanks for making this a reality. I appreciate your commitment to provide fixes and updates over an extended period of time.

Here it is on my TV...

![image](https://github.com/vbguyny/ws4kp/assets/169946395/c3303605-15a2-45ee-ae65-b37db6d6277a)

**Comment by TheSystemGuy1337** [comment]
Since it's an API key problem (I guess weather.com blacklisted vbguyny's key), how do I get my own API key and run this service locally?

**Comment by vbguyny** [comment]
This is fixed now thanks !
