### ISSUE TITLE
Severe Storm Warnings/Tornado Warnings Not Showing

### ISSUE THREAD

**Issue by zonexero** [vbguyny/ws4kp#119]
Was just checking out some severe weather in a few area, as always, the sim is great.  As writing this now, there is a severe thunderstorm warning for Crossville TN, but it's not showing in the hazardous weather feed, likewise a tornado warning also not showing for Temple TX.   Not sure if it's a glitch or something else going on.   Thanks again, this still is truly awesome!

**Comment by vbguyny** [comment]
Appears to be working:

![image](https://github.com/vbguyny/ws4kp/assets/871502/7317cf2a-278a-42a4-b9df-dd44be85e4e9)
![image](https://github.com/vbguyny/ws4kp/assets/871502/ba64f37a-6f9e-43e2-828c-c7ebe3df5abd)

My guess is that the page for https://api.weather.gov/alerts/active.atom and the Zone used to get the weather didn't have an alert in the api.weather.gov end-point. That being the case, there really isn't much that can be done to correct this.
