### ISSUE TITLE
Nariation not working 

### ISSUE THREAD

**Issue by jediknight36** [vbguyny/ws4kp#121]
I have two streams going right now. One, the nariation button just doesn't work at all. The other, the icon shows muted or not muted, but no nariation either way. Music is unaffected.

**Comment by vbguyny** [comment]
Hello @jediknight36 

Could you please indicate which operating system and browser you are experiencing the issue?

**Comment by jediknight36** [comment]
I was on Opera for Android and Chrome for windows. It seems to be back now, but was off for a while.

**Comment by vbguyny** [comment]
@jediknight36 not sure what happened but I'm glad that it is working again for you.
