### ISSUE TITLE
Display RSS feed for Scroll Text?

### ISSUE THREAD

**Issue by karnov77** [vbguyny/ws4kp#15]
Hi vbguyny,

Love your WeatherStation 4000 simulator!! Great work!

Is there any way currently, or a feature that can be added in the future, that will allow an RSS feed to be displayed as the Scroll Text?

Thanks!
Andrew

**Comment by vbguyny** [comment]
@karnov77 Thanks!
Nobody has ever requested RSS feeds before.  Do you have one in mind?  If so, could you provide the link and I'll take a look.
Thanks.

**Comment by karnov77** [comment]
Hi! I was just thinking of a feature where an RSS feed URL could be entered and then the feed would display as the scrolling text. If you're thinking of implementing it as selecting from a list of RSS feeds, I would say the major news ones such as...

CNN: http://rss.cnn.com/rss/cnn_topstories.rss
Reuters: http://feeds.reuters.com/reuters/topNews

Thanks!
Andrew

**Comment by IoIxDButStronger** [comment]
Hey, I was just wondering what the priority of this feature was? I'd love to see this implemented as well.

**Comment by vbguyny** [comment]
I don't have the time right now to invest in this feature.  That being said anyone is welcome to fork the project, make the change, and make a pull request.

**Comment by vbguyny** [comment]
This feature has been implemented in this following commit:  https://github.com/vbguyny/ws4kp/tree/62ed00de598c6a294a05507cd78e43f4225630ad

**Comment by vbguyny** [comment]
The new feature is available in v1.62:

![RssFeed](https://user-images.githubusercontent.com/871502/118012681-52d54a00-b31f-11eb-8c9d-1c04038e63a5.png)
