### ISSUE TITLE
API Change suggestion

### ISSUE THREAD

**Issue by Psukeo** [vbguyny/ws4kp#16]
Well, now, it's been a long time since I've been here, huh? Brings back some good memories, indeed...now, what I'm thinking here is that the data for the 4000+ should come from the NWS API, rather than the Weather Underground API. This would most likely fix the Almanac and Marine Forecast problems, considering that it's coming from the API of the source of the forecasts, rather than an API relaying that source's forecasts. I don't know whether or not the Wunderground API is the only one, but, it seems to be that it is the main one or, at least, a major one.

**Comment by Psukeo** [comment]
Ahh, a well thought-out plan, indeed...though, it is much disappointing that they wouldn't support the APIs any longer. I'll see if any of the forks have fixed the Almanac and Marine Forecast problems. Hopefully you get enough time next year to try and fix those problems! I wish you a happy holidays!

**Comment by vbguyny** [comment]
@Psukeo I fixed the Almanac.  I'll see what I can do about the Marine Forecast.  Happy holidays!

**Comment by Psukeo** [comment]
Ahh, that's good to hear! The night, indeed, has returned...and so has choppy waves! Glad to see both of them return after so long. :D
I have some other suggestions I'll make tomorrow, but, I think I'll make those tomorrow, seeing as it's getting a bit late over here. Hope you have a swell night, and a happy new year! .o./

**Comment by vbguyny** [comment]
Sounds good.  Please create new issues for any additional suggestions.  I'm closing this one.
