### ISSUE TITLE
Newer icons

### ISSUE THREAD

**Issue by Psukeo** [vbguyny/ws4kp#17]
I propose that the WS4000+ site should use the [regional icons from Spring 1994](http://files.twcclassics.com/downloads/1994%20Regional.zip) onward. A problem I have with the use of the 1992 icons is that most, if not all of them, get compressed when displayed, the biggest offender of said problem the Mostly Cloudy icon and the Scattered Precipitation icons. While I do understand that it's a problem that is inherit to 4000+, I believe using the newer ones will at least result in less compression in those biggest offenders.
I do realize, too, that @malekmasoud created some of the icons (namely, the night-time variants of the Scattered Precipitation icons). I was thinking about addressing this by creating versions of his originals that fit with the design of their re-designed counterparts if, and only if, Malek does not want to create new ones and he allows me to make these redesigns.
I'll send them via this topic if that is the case. Hope to get back to you soon.

**Comment by malekmasoud** [comment]
> I propose that the WS4000+ site should use the [regional icons from Spring 1994](http://files.twcclassics.com/downloads/1994%20Regional.zip) onward. A problem I have with the use of the 1992 icons is that most, if not all of them, get compressed when displayed, the biggest offender of said problem the Mostly Cloudy icon and the Scattered Precipitation icons. While I do understand that it's a problem that is inherit to 4000+, I believe using the newer ones will at least result in less compression in those biggest offenders.
> I do realize, too, that @malekmasoud created some of the icons (namely, the night-time variants of the Scattered Precipitation icons). I was thinking about addressing this by creating versions of his originals that fit with the design of their re-designed counterparts if, and only if, Malek does not want to create new ones and he allows me to make these redesigns.
> I'll send them via this topic if that is the case. Hope to get back to you soon.

I have granted your wishes for I am now presenting you the following 1994 icons, some of which I made up myself:
![mostly-cloudy-1994-alt](https://user-images.githubusercontent.com/25880200/50536654-9d761300-0b24-11e9-82f2-6fe0e246a12b.gif)
![partly-clear-1994](https://user-images.githubusercontent.com/25880200/50536653-9d761300-0b24-11e9-9c3c-7239696b46d7.gif)
![scattered-snow-showers-1994](https://user-images.githubusercontent.com/25880200/50536655-9d761300-0b24-11e9-924e-446eebf1fc6c.gif)
![scattered-snow-showers-night-1994](https://user-images.githubusercontent.com/25880200/50536703-1d9c7880-0b25-11e9-8b15-afd26fc9dcc8.gif)
![scattered-tstorms-1994](https://user-images.githubusercontent.com/25880200/50536719-44f34580-0b25-11e9-9820-8ba65fcd0fea.gif)
![scattered-tstorms-night-1994](https://user-images.githubusercontent.com/25880200/50536701-1d9c7880-0b25-11e9-9b56-defa55e77f31.gif)
![scattered-showers-1994](https://user-images.githubusercontent.com/25880200/50536718-44f34580-0b25-11e9-8b06-8673879b2518.gif)
![scattered-showers-night-1994](https://user-images.githubusercontent.com/25880200/50536702-1d9c7880-0b25-11e9-89fc-0b8e8c4f2a52.gif)
![heavy-snow-1994](https://user-images.githubusercontent.com/25880200/50536734-723ff380-0b25-11e9-8711-f0e0d284de8a.gif)

**Comment by vbguyny** [comment]
Thanks, guys! I'll import them as soon as I can.

**Comment by vbguyny** [comment]
Done!  (Added in v1.36)
