### ISSUE TITLE
Extended Forecast, Almanac, Local Radar Automated issue,

### ISSUE THREAD

**Issue by mlbailey1308** [vbguyny/ws4kp#18]
https://github.com/vbguyny/ws4kp/issues/7#issuecomment-451012944

**Comment by vbguyny** [comment]
Fixed in version 1.39

**Comment by vbguyny** [comment]
Hello @mlbailey1308 did you happen to find anyone that was able to help you get the WeatherStar 4000+ working?

**Comment by mlbailey1308** [comment]
I am trying to get the weather link added to my website as a link now and change the Weather Star logo to my stations logo.  Can you give me any instructions on how to do this so I can pass this on to my web designer??
Maurice
    On Sunday, March 10, 2019, 4:07:42 PM EDT, vbguyny <notifications@github.com> wrote:  
 
 
Hello @mlbailey1308 did you happen to find anyone that was able to help you get the WeatherStar 4000+ working?

**Comment by vbguyny** [comment]
@mlbailey1308 Hello!

To change the logo, you need to update the method `DrawLogoImage` in the script file "twc3.js".  Look for the following code:

```
var DrawLogoImage = function (context)
{
    if (!_LogoImage)
    {
        _LogoImage = new Image();

        _LogoImage.onload = function ()
        {
            //SmoothingEnabled(context, true);
            context.drawImage(_LogoImage, 50, 30, 85, 67);
        };
        //LogoImage.src = "Images/Logo1.png";
        //_LogoImage.src = "Images/Logo3.gif";
        _LogoImage.src = "Images/Logo3.png";
    }
    else
    {
        context.drawImage(_LogoImage, 50, 30, 85, 67);
    }
};
```

Could you please provide the link to your website to that can I have a better understanding of what it is you are trying to accomplish?

**Comment by mlbailey1308** [comment]
Thanks for your response.  The link below is our website that is being built that is currently on test server.  Your assistance is greatly appreciated.
WFETTV29 – Watch Family Entertainment TV


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
WFETTV29 – Watch Family Entertainment TV


 |

 |

 |




Maurice
    On Wednesday, July 17, 2019, 3:49:05 PM EDT, vbguyny <notifications@github.com> wrote:  
 
 
@mlbailey1308 Hello!

To change the logo, you need to update the method DrawLogoImage in the script file "twc3.js". Look for the following code:
var DrawLogoImage = function (context)
{
    if (!_LogoImage)
    {
        _LogoImage = new Image();

        _LogoImage.onload = function ()
        {
            //SmoothingEnabled(context, true);
            context.drawImage(_LogoImage, 50, 30, 85, 67);
        };
        //LogoImage.src = "Images/Logo1.png";
        //_LogoImage.src = "Images/Logo3.gif";
        _LogoImage.src = "Images/Logo3.png";
    }
    else
    {
        context.drawImage(_LogoImage, 50, 30, 85, 67);
    }
};

Could you please provide the link to your website to that can I have a better understanding of what it is you are trying to accomplish?

**Comment by vbguyny** [comment]
@mlbailey1308 the link didn't load in Github.  Is this the URL to your site: https://fetv.tv/ ?

**Comment by mlbailey1308** [comment]
No that’s not my site.  My site is being built and the test server is the link I sent you.  Not sure why you could not open.  Can open it outside of github?  I had no problem opening.

**Comment by vbguyny** [comment]
@mlbailey1308 I didn't get a link.  Could you please send it again?  Thanks!

**Comment by mlbailey1308** [comment]
https://www.weightlosssurgeryinc.com/test_web/


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
WFETTV29 – Watch Family Entertainment TV


 |

 |

 |



This is the link

    On Wednesday, July 17, 2019, 9:55:27 PM EDT, vbguyny <notifications@github.com> wrote:  
 
 
@mlbailey1308 I didn't get a link. Could you please send it again? Thanks!

**Comment by vbguyny** [comment]
@mlbailey1308 Got it!  It looks like you are trying to embed my site into your site from an iframe.  There are two issues with this approach:
1. You are not going to be able to make modifications to the code using this method because the version on my site cannot be modified.  You will have to download the code from this github repo and run the site directly from your server before you will be able to change the logo.
2. My site is being ran from my personal PC so it isn't going to be able to handle any sizable web traffic, therefore, it would be a better option to host it on your own server.

**Comment by mlbailey1308** [comment]
Ok, send me the exact code that needs to be added to my server with my logo and I will forward it to my web designer.
Thanks in advance for your assistance.
Maurice
    On Wednesday, July 17, 2019, 10:32:55 PM EDT, vbguyny <notifications@github.com> wrote:  
 
 
@mlbailey1308 Got it! It looks like you are trying to embed my site into your site from an iframe. There are two issues with this approach:
   
   - You are not going to be able to make modifications to the code using this method because the version on my site cannot be modified. You will have to download the code from this github repo and run the site directly from your server before you will be able to change the logo.
   - My site is being ran from my personal PC so it isn't going to be able to handle any sizable web traffic, therefore, it would be a better option to host it on your own server.

**Comment by mlbailey1308** [comment]
Is this what my web designer need to add weatherstar to my site?


Setup
It is recommended that you download all of the source code to a folder and use Internet Information Services (IIS) 7.5 or later with ASP .NET 4.5 or later to create a virtual directory which points to this folder.
If you plan on exposing this site publicly, you will need to update the code in CORS/Default.aspx to have your public IP address and domain name:
 switch (Page.Request.Url.Host) { case "localhost": case "192.168.2.98": case "battaglia.ddns.net": case "[Your domain here]": OkToProcessRequest = true; break; }
Thanks in advance for your response.  If this is not correct, please provide if you don't mine.
ML B    On Wednesday, July 17, 2019, 10:35:56 PM EDT, ML Bailey <03089697@bellsouth.net> wrote:  
 
  Ok, send me the exact code that needs to be added to my server with my logo and I will forward it to my web designer.
Thanks in advance for your assistance.
Maurice
    On Wednesday, July 17, 2019, 10:32:55 PM EDT, vbguyny <notifications@github.com> wrote:  
 
 
@mlbailey1308 Got it! It looks like you are trying to embed my site into your site from an iframe. There are two issues with this approach:
   
   - You are not going to be able to make modifications to the code using this method because the version on my site cannot be modified. You will have to download the code from this github repo and run the site directly from your server before you will be able to change the logo.
   - My site is being ran from my personal PC so it isn't going to be able to handle any sizable web traffic, therefore, it would be a better option to host it on your own server.

**Comment by vbguyny** [comment]
Yes those are basically the instructions.  Use the following link to download the latest version of the site: https://github.com/vbguyny/ws4kp/archive/master.zip

**Comment by mlbailey1308** [comment]
Thanks.  Is it possible to load on our site even if it is PHP rather than ASP?

MLB

**Comment by vbguyny** [comment]
If it is a Windows server you can run both PHP and ASP.NET
It needs to be at least Windows 2012 or later.

**Comment by mlbailey1308** [comment]
It’s a Linux server.

**Comment by mlbailey1308** [comment]
Any hope with it working by loading it on Linux server?

**Comment by vbguyny** [comment]
I have no experience using a Linux server.  However, I would suggest you have your web guy looking around the web.  For example, I found this: https://www.mono-project.com/docs/web/aspnet/

**Comment by mlbailey1308** [comment]
Is it possible you could put our logo in place of the weatherstar 4000 and we use app as is on our site?
ML B
    On Thursday, July 18, 2019, 10:52:15 PM EDT, vbguyny <notifications@github.com> wrote:  
 
 
I have no experience using a Linux server. However, I would suggest you have your web guy looking around the web. For example, I found this: https://www.mono-project.com/docs/web/aspnet/

**Comment by vbguyny** [comment]
Hello @mlbailey1308 
The steps to change the logo are as follows:
1. Download the code to your server clicking this link: [https://github.com/vbguyny/ws4kp/archive/master.zip](https://github.com/vbguyny/ws4kp/archive/master.zip)
2. Following the directions as indicated on my previous post: [https://github.com/vbguyny/ws4kp/issues/18#issuecomment-512542620](https://github.com/vbguyny/ws4kp/issues/18#issuecomment-512542620)
