### ISSUE TITLE
Ability to Change Flavors

### ISSUE THREAD

**Issue by btrains** [vbguyny/ws4kp#19]
I have a suggestion to allow the end user to select either a default flavor like used on the original 4000, or to allow the end user to pick and choose which frames to view. Personally I have no use for the Travel Cities Forecast, and especially if I were to run this on a loop as a continuous display of weather information, I'd like to be able to adjust which screens to show and which to skip. 

Other than that, it's a fascinating take on the original. Half fantasy, half simulation. Great work.

**Comment by vbguyny** [comment]
Hello @btrains!
Thanks for the feedback!  I'll take a look to see what would be involved to make this change.

**Comment by vbguyny** [comment]
BTW, one of the forks to this repo appears to have implemented this feature with checkboxes to select which options you want to see: https://weatherstar.netbymatt.com/
