### ISSUE TITLE
Regional forecast does not show my city.

### ISSUE THREAD

**Issue by crenshawthorpe** [vbguyny/ws4kp#20]
I honestly can't remember if this is normal (unsure how these are chosen), but the regional forecast map does not show my city, which is Tucson and is substantially larger than a few of the cities on this map.

https://i.imgur.com/sDb0Uh6.png

Also, one of the nearby locations in Tucson International Airport, which is a mouthful and spans off of the edge of the map like so:

https://i.imgur.com/Jgmk5TH.png

Unsure how that was handled initially by TWC but it feels like it should scroll or something.

If this is normal/expected, just close.  I love what you've done here by the way.  This is a trip.

**Comment by vbguyny** [comment]
Hello @crenshawthorpe!  I have a hard-coded list of cities.  I'll see what I can do about adding Tucson as well as fixing that long city name issue.

Glad you enjoyed my weather site!

**Comment by vbguyny** [comment]
@crenshawthorpe, the bugs have been fixed.  Check out the latest version of the site :)
