### ISSUE TITLE
Music tracks by Trammell Starks

### ISSUE THREAD

**Issue by mmcfly566** [vbguyny/ws4kp#22]
I think that the songs by Trammell Starks that appeared on the Weather Channel around 1997 should be added.

**Comment by vbguyny** [comment]
@mmcfly566 I can do that.  I found the music here: [https://twcclassics.com/audio/artists-t.html](https://twcclassics.com/audio/artists-t.html)

**Comment by vbguyny** [comment]
The website has been update with the music in version 1.44 which is now live: https://battaglia.ddns.net/twc/
