### ISSUE TITLE
LAMP Hosting

### ISSUE THREAD

**Issue by chandrachurdas** [vbguyny/ws4kp#24]
Hi,
Can the app be installed on shared LAMP web server. I would really appreciate any kind of help on this.

Regards,
Chan

**Comment by vbguyny** [comment]
Hello @chandrachurdas 
I'm afraid not.  LAMP stands for Linux, Apache, MySQL and PHP.  My code currently uses Windows and ASP.NET
It would be great is someone could fork this repo and create a version of the WeatherStar 4000+ that worked on a LAMP server :/
