### ISSUE TITLE
System Hanging on Radar Imagery

### ISSUE THREAD

**Issue by KubbaYioka** [vbguyny/ws4kp#25]
Hello,

I've been running WeatherStar 4000+ on my Raspberry Pi 3B+ with the latest installation of Raspbian Stretch. I have an industrial cooling fan keeping my set up chilly.

When I let the 4000+ run in Chromium, it can usually complete a few loops before eventually freezing on radar imagery. The system itself will hang and become unresponsive. I haven't noted any abnormally high CPU usage, but I have not checked the RAM just yet. 

Any thoughts would be helpful.

**Comment by vbguyny** [comment]
Hello, @KubbaYioka !
Do you happen to have the Auto Refresh checkbox checked?  If so, see if the issue happens when it is unchecked.

**Comment by KubbaYioka** [comment]
Hello,

I tested it today, and no, I don't have the issue when auto-refresh is off.

**Comment by vbguyny** [comment]
@KubbaYioka I updated the website, could you please see if it works now?

**Comment by KubbaYioka** [comment]
Sorry about the late reply. 

I did not experience the same problem after your update. I let it run for a good deal of time. 

I think this is resolved, but I'll message if it happens next time I let it run (everything is put up for remodeling atm).

Thank you!

**Comment by vbguyny** [comment]
Great!  Thanks @KubbaYioka
