### ISSUE TITLE
Daypart Forecast

### ISSUE THREAD

**Issue by Psukeo** [vbguyny/ws4kp#3]
This is a concept I've wanted for quite a time: the Daypart Forecast.

Now here's the source I've gotten for this feature. If it doesn't work, I'll try to find another source, unless you want to do it.
http://forecast.weather.gov/MapClick.php?lat=42.8326&lon=-106.329&lg=english&&FcstType=digital

The Daypart Forecast, also known as the Daily Planner on the Intellistar, is one page that displays an hourly forecast for the area in a bar graph for it's temperature, with the forecast above, at a set level. The hours used for it in the WSXL and IS are Midnight, 6 am, Noon, 3 pm, 5 pm, and 8 pm. However, the hours I want to be used is Midnight, 3 am, 6 am, 9 am, Noon, 3 pm, 6 pm, and 9 pm, to make it more useful.

I hope this will be implemented, in order to make the WS4K+ more useful for people.

**Comment by vbguyny** [comment]
@Psukeo: This is amazing!

I did some additional research and the link that I would use in my web app would be http://forecast.weather.gov/MapClick.php?lat=42.8326&lon=-106.329&FcstType=json because it will return the data into a JSON format which is easier to parse ;)

However, I am having a hard time understanding exactly how you visualize this on the screen.  Could you either mock something up for me or provide me a link to something that demonstrates what you are looking for?

Thanks.

**Comment by Psukeo** [comment]
Here's one concept. It's from the same vid i showed you for the 8-City Latest Observations.

https://youtu.be/gCc83R13Zs8?t=27s

Just use the bars used for the Air Quality Forecast, flip them on their side, and there you go!

**Comment by vbguyny** [comment]
Very clear now. Thanks!

**Comment by Psukeo** [comment]
You're welcome! Hopefully, it should be as easy to do as the nighttime forecast, with the JSON data.

**Comment by Psukeo** [comment]
Just checking, but how's the Daypart Forecast coming along? Hopefully it's not too bothersome for you.

Also, made a new icon to go with AM Snow - PM Snow!
![pm snow](https://cloud.githubusercontent.com/assets/18102459/23186364/7eb5f562-f84c-11e6-9f82-dffc774af393.png)

**Comment by vbguyny** [comment]
I haven't worked on it yet.  I cannot say when it will be done at this point.

Thanks for the image and link to the music.  In the future please create a unique issue for each topic otherwise it is going to be pretty hard for me to track the changes!

**Comment by Psukeo** [comment]
Sorry! :P

I want to email the icons and status updates to you, so that there isn't any spam in these issue threads.

**Comment by Psukeo** [comment]
Alright, so, I just recently got an idea pertaining to the name of this segment. I think that, in honor of the now practically defunct NWS Short Term Forecast, what with the tabular forecast functionally taking it's place, this segment should not be named Daypart Forecast, but, rather, the Local Update, after the April 1995 - Summer 2002 segment of the same name. It's fair if you disagree with me, this is just an idea I'm throwing at the wall here.

**Comment by vbguyny** [comment]
Is there a YouTube video or picture that shows what it looked like back in the day?

**Comment by Psukeo** [comment]
Right here! https://youtu.be/2WsCLIQ_lMs?t=15
As I alluded to before, this segment used to display Short Term Forecast if one was issued from the NWS.

**Comment by vbguyny** [comment]
Thanks. I see that this is different than the concept with the bars that you posted above from 2/20/17.

**Comment by Psukeo** [comment]
Much so! In fact, this product actually changed the layout of the flavor it was on depending on how many screens the Short Term Forecast took up. For example, a D flavor (the same flavor seen in the video, if I'm remembering it right) with no Local Update screens would have the Extended Forecast at the end, as well as having the Current Radar take up the spot where the Local Update was. I don't think we can implement the exact same product into the WS4000+, mainly as the main candidates for taking up the Short Term Forecast's reign (Hazardous Weather Outlook and Hydrologic Outlook) either happen only a tiny smidge more often than the STF, or are too specialized to fully replicate the function of the now defunct product. The best thing to do is to label the Daypart Forecast as the Local Update, as it covers roughly the maximum amount of time the STF did(12 hours).

**Comment by vbguyny** [comment]
At this point I am not going to be making this additional to the site.  It requires hours that I don't have available for the foreseeable future.

**Comment by vbguyny** [comment]
BTW, one of the forks to this repo appears to have implemented this feature as "Hourly Forecast"
https://weatherstar.netbymatt.com/
