### ISSUE TITLE
Severe Warnings

### ISSUE THREAD

**Issue by zonexero** [vbguyny/ws4kp#31]
Is there a way to include severe weather crawls on the bottom area like the original?  It would be helpful when there is severe thunderstorms, tornadoes, ect.  I have seen the bulletins in the top area as the original, but never any severe on lower crawl.

**Comment by vbguyny** [comment]
@zonexero, Hello!
There is no option for this in the current version. I flagged your issue as a feature request so it is possible that this may be included in a future release.

**Comment by zonexero** [comment]
thank you

________________________________

**Comment by zonexero** [comment]
This emulator is just great, I hate asking for anything, but is there a way to stretch the 4x3 fullscreen to 16x9 widescreen mode? I know the other emulator taiganet did will do this in fullscreen mode.  I use this one on airplay at my house, some of my monitors do not allow for stretch mode. I realize this throws off the resolution a bit, but really it looks fine on the monitors I can stretch it out on.  I have tried playing around with the download version you have but cannot find anything there to do it.  Thanks

**Comment by jacobrillema** [comment]
Is this what we are looking for? https://www.youtube.com/watch?v=Jo81qTVx15g

**Comment by vbguyny** [comment]
Hello @jacobrillema,

Yes, thanks for the clarification.  At this point I don't have any plans for adding that option into the site.  We do have the full screen version, but it doesn't appear initially.  That being said, if there is ever an alert the user can tap on it and go to it straight away.

I am going to keep this issue open for future reference.

**Comment by vbguyny** [comment]
The change has been added in the following commit: https://github.com/vbguyny/ws4kp/commit/8aeb9d8652271e0e56194be65368cd7c406402d9
The website has been updated!
