### ISSUE TITLE
Radar basemap

### ISSUE THREAD

**Issue by mbates14** [vbguyny/ws4kp#32]
Question, how did you obtain/create the radar basemap? 

the one that is being used is heavily pixilated/compressed and was wondering if you had the master files for that. In case your curious, i am working on a project getting the original machine running again using custom software and I have a distinct lack of graphics. 

thanks.

**Comment by vbguyny** [comment]
Hello @mbates14 it was years ago, however, I believe I found doing a Google search but I don't remember what text I used to find it.  All of the assets related to this project are located here on Github.  Believe me, I wish I had a better high res version of this map.

**Comment by mbates14** [comment]
Ah, ok. Well I got something "close" by using QGIS but it took a lot of work. however the airport codes and things have to be added manually. Not sure what font those are in.
