### ISSUE TITLE
Recommend removal of music track with voice

### ISSUE THREAD

**Issue by nivex** [vbguyny/ws4kp#33]
The track "Trammell Starks - All That Jazz" has some of the original TWC narration in it. It starts by saying "Currently the temperature is 38 degrees with light snow". This is a bit jarring when it's 65 degrees and sunny outside :)

**Comment by nivex** [comment]
"Trammell Starks - Island Groove" has a similar artifact.

**Comment by vbguyny** [comment]
@nivex Thanks for noticing that!  I'll fix that right away :)

**Comment by vbguyny** [comment]
Done!  Website updated.  Thanks again!!
