### ISSUE TITLE
Alternative CORS services not working

### ISSUE THREAD

**Issue by nivex** [vbguyny/ws4kp#35]
crossorigin.me and anyorigin.com are gone.

whateverorigin.org passes data, but ironically does not respond with the necessary `Access-Control-Allow-Origin: *` header.

You may want to clear those out of readme and twc3.js.

**Comment by vbguyny** [comment]
@nivex Will do!  Also if you know of any other alternate CORS services let me know!

**Comment by vbguyny** [comment]
Checked in!
