### ISSUE TITLE
forecast.weather.gov appears to allow CORS

### ISSUE THREAD

**Issue by nivex** [vbguyny/ws4kp#36]
I'm seeing an `Access-Control-Allow-Origin: *` coming back from forecast.weather.gov. Looks like those calls might not have to go through the CORS relay anymore.

```
$ curl -I 'https://forecast.weather.gov/MapClick.php?FcstType=dwml&lat=34.2257&lon=-77.9447'
HTTP/2 200 
server: Apache
x-nids-serverid: www3.md
x-ua-compatible: IE=Edge
access-control-allow-origin: *
content-type: text/xml
expires: Sat, 18 Apr 2020 21:42:09 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Sat, 18 Apr 2020 21:42:09 GMT
content-length: 0
strict-transport-security: max-age=31536000 ; includeSubDomains ; preload
```

**Comment by vbguyny** [comment]
@nivex understood, but I was in contact with someone at NOAA a while back when they were upgrading their APIs and they mentioned that they would change that at some point.  It is doing this by design :)
