### ISSUE TITLE
GetClosestCurrentWeather runs forever if no valid data found

### ISSUE THREAD

**Issue by nivex** [vbguyny/ws4kp#38]
During testing of a new CORS proxy I discovered that GetClosestCurrentWeather (twc3.js:341) will continue to run forever, increasing distance and trying a request again immediately. In the ~40 seconds before I reloaded (I was working on a fix in the background) it had made over 1500 requests. I suggest adding an escape function if the distance exceeds a certain threshold (100 miles?) and/or waiting some amount of time before increasing the distance and trying again.

**Comment by vbguyny** [comment]
@nivex Good one!  I never thought that it would fail but it would explain why sometimes it would never finish loading.  I'll  take a look.

**Comment by vbguyny** [comment]
@nivex fixed!
