### ISSUE TITLE
Hawaiian Cities

### ISSUE THREAD

**Issue by Psukeo** [vbguyny/ws4kp#4]
So, I noticed this a while ago, but never mentioned it til now...there are barely any cities on the Hawaiian map. The only 3 are Honolulu, Bradshaw AAF, and Kamuela/Waimea, and the last one only shows up if the location is Lihue. My suggestion is to get rid of Kamuela/Waimea, then add the new cities on the map.

![hawaii problem 1](https://cloud.githubusercontent.com/assets/18102459/23239315/1614adba-f92c-11e6-83c4-ed881d265cdd.PNG)

That would make the Hawaiian Regional Map a lot more informational.

**Comment by vbguyny** [comment]
I decreased the distance of the allowable cities for HW which in turn will display more in the regional maps.
This issue is fixed in version 1.37
