### ISSUE TITLE
Weather.gov is starting to phase out old weather API.

### ISSUE THREAD

**Issue by vbguyny** [vbguyny/ws4kp#42]
For years, the site was able to get weather data in XML by hitting the forecast.weather.gov/MapClick.php page with the FcstType=dwml and the lat,lon as query arguments.  However, recently it appears that weather.og is phasing that out by simply having the site redirect the user to the page using a look up by zoneid.

For example:
```
Url: https://forecast.weather.gov/MapClick.php?FcstType=dwml&lat=33.749&lon=-84.388
Redirects to: https://forecast.weather.gov/MapClick.php?zoneid=GAZ033&zflg=1
```
However, the following URL currently works:
```
https://forecast.weather.gov/MapClick.php?FcstType=dwml&lat=40.81564&lon=-73.001
```

The new API is available, however, it isn't 100% working.  According to their FAQ (https://weather-gov.github.io/api/general-faqs), they say that they still support the XML format but I would need to do testing to confirm this.

**Comment by vbguyny** [comment]
Update: I sent NOAA an email also opened an issue on their Github page: https://github.com/weather-gov/api/issues/79

**Comment by scadergit** [comment]
It's getting redirected because the forecast data is not available. If you look at the forecast web page for that location, it is likely  also redirecting to the zone forecast page. This is due to a larger issue NCO is working on.

**Comment by vbguyny** [comment]
@scadergit thanks for the update! I got an email yesterday saying that they resolved the issues and I can confirm the site works again.
