### ISSUE TITLE
Images folder?

### ISSUE THREAD

**Issue by netbymatt** [vbguyny/ws4kp#44]
There seems to be a lot going on in the images folder that isn't directly related to displaying weather graphics. Can you provide some explanations of the extra folders, -1, -2 and other files that seem to either be obsolete or work-in-progress?

**Comment by vbguyny** [comment]
Hello @netbymatt 

Those folders are there work-in-progress.  I have been working with some generous people in the community that have been providing me assets which I have yet to incorporate into the site.

Thanks,
-Mike
