### ISSUE TITLE
Support for Australian weather

### ISSUE THREAD

**Issue by gabearthur4** [vbguyny/ws4kp#46]
Is it possible to add an option to see Australian weather? Could be taken from the National Bureau of Meteorology, and would make a great addition!

**Comment by vbguyny** [comment]
Hello, @gabearthur4!

Thank you for your interest in the WeatherStar 4000+, however, I have no plans on extending the support to outside of the US at this time.  You are welcome to fork this project and take make the modifications yourself!

Thanks,
-Mike
