### ISSUE TITLE
Restrict CORS endpoint to certain domains 

### ISSUE THREAD

**Issue by srt4** [vbguyny/ws4kp#49]
When looking at the requests made from my browser, there were a lot of `/twc/cors?u=`. Accessing that URL, but replacing the `u` query parameter with e.g. `https://google.com` results in the Google homepage being relayed. It seems an attacker could potentially use this endpoint to DoS a server. 

It may be worth restricting this endpoint to known-good endpoints, e.g. `iastate.edu`, `airnowapi.org`, `forecast.weather.gov`.

**Comment by vbguyny** [comment]
Hello @srt4 good find!  Thanks :)

**Comment by vbguyny** [comment]
Fixed and the site has been update!
https://github.com/vbguyny/ws4kp/commit/813f4428216f3903774e72149bfe044cb1b6ed6b
