### ISSUE TITLE
Weather.gov is updating its website.

### ISSUE THREAD

**Issue by vbguyny** [vbguyny/ws4kp#5]
It has been brought to my attention that weather.gov will be performing major updates to their site on March 7, 2017 which directly affect the Weather Star 4000+.  It is still unclear at this time to measure the full scope of how these changes will affect my site but at this point I am freezing any and all changes until the new weather.gov site has been implemented.

More intimation about the changes here: http://www.weather.gov/cae/pointnclickchange

**Comment by Psukeo** [comment]
I really hope this doesn't kill this project.

**Comment by vbguyny** [comment]
@Psukeo fingers crossed!

**Comment by Psukeo** [comment]
The reckoning is upon us.

One day remains until change.

**Comment by Psukeo** [comment]
They just pushed it to April 4th!

**Comment by vbguyny** [comment]
Ok, it looks like their APIs are live now (https://forecast-v3.weather.gov/documentation).  However there are issues.  I got a few 500 error code while trying to invoke them.  I just sent an email to someone at the NWS to see if they can forward my questions to someone more technical.

**Comment by vbguyny** [comment]
Update: I am working with a technical person from NOAA to get the documentation finished and assist resolving the internal server errors on their end.  The ETA for issues being resolved is near the end of March.  Hopefully I can get a head of the weather.gov change!

**Comment by Psukeo** [comment]
That's good! I hope all of the other issues are finished by the end of April!

**Comment by vbguyny** [comment]
I have put the entire project on hold until I get the site working with the new APIs.  The reason is because any change that I make now will most likely have to be updated again.  Unless it is a seriously issue, it will have to wait.

**Comment by vbguyny** [comment]
I have been reporting multiple issues with the new API directly to the chief software developer in charge at NOAA.  I would not be surprised if they pushed the change off even further than April 4th!

**Comment by vbguyny** [comment]
Update: I have been emailing NWS/NOAA fairly regularly and in the last communication they indicated they are working on issues in their data center.  I also reported additional issues with their new API.  I inquired if it was possible to continue supporting their existing APIs but I am doubtful that their response being in my favor.

**Comment by vbguyny** [comment]
I just word back that they will be killing the current APIs in favor of the new ones.  However I am still unable to access all of the APIs since they are still ironing out issues on their end.

**Comment by Psukeo** [comment]
Has any progress been made in the technical front in the last week? Not to be rude, just wondering.

**Comment by vbguyny** [comment]
Here is the last email I received from NOAA:

> Hi Mike,
> 
> We are in the process of testing out issues that have been reported independently from the preview forecast page.  Once we get through testing, we plan to address this and other reported issues on the preview page.
> 
> Please continue to provide us with feedback and we'll make sure to continue following up.
> 
> Thanks.
> 
> 
> Paul Iwugo, PMP 
> Chief, Software Development Branch
> NOAA | NWS | NCEP | NCO
> office - 301.683.1303
> mobile - 301.543.0408
> paul.iwugo@noaa.gov
>

**Comment by vbguyny** [comment]
Update: According to NOAA, they plan on rolling out the new APIs tomorrow around 10 AM EST.  I expect the website to be down at that time.

**Comment by malekmasoud** [comment]
@vbguyny Will that mean tonight's gonna be WeatherSTAR 4000+'s final night online?

**Comment by vbguyny** [comment]
@malekmasoud that means it will be down.  I won't say the final night.  I just have a lot of work a head of me to get it working again.  :-/

**Comment by vbguyny** [comment]
NOAA had to roll back the update.  They plan on rolling it out now for Jun 19th.

**Comment by vbguyny** [comment]
Update: The June 19th roll out has been pushed back to August 14th.

**Comment by vbguyny** [comment]
The August 14th roll out did not happen.  My contact at NOAA said there is no ETA at this time.  I'll post something as soon as I get a date.

**Comment by vbguyny** [comment]
I'm closing this issue as NOAA appears to have lost the funding to push out the new APIs.  Luckily, the website still works with the old ones.
