### ISSUE TITLE
Ability to disable the bottom bar and use the mouse buttons as navigations.

### ISSUE THREAD

**Issue by IoIxDButStronger** [vbguyny/ws4kp#51]
Hi, I don't know how many other people have done this but I've hooked up a Raspberry Pi to my old CRT TV and I am currently displaying this site to it. It works well and looks very nice on this TV, but unless I'm missing something, this is mostly operated by the mouse pointer. It seems a keyboard would work too but I don't have a spare keyboard to hook up at all times to this Pi, so I've been mostly using the mouse. This is an unfortunate downside because when I put the site into full screen, the bottom navigation bar is always there, making it not appear on the screen and having this black bar. My current solution is zooming out to have said bar be small, but then I can't zoom back in with only the mouse, so when I want to display other things on the TV it's very cumbersome to have to click the fullscreen button (which I can't see as this CRT is slightly curved) and get out. 

I think it would be nice, therefore, to have a mouse buttons only mode; exit full screen with the middle mouse button, activate or go back with the left mouse button, and go forward with the right mouse button. I don't see a need for the mute button to be assigned to anything because I just have the site on full volume, and use the TV's internal volume control. The refresh button also isn't useful but if it needs to be assigned to anything, it could be done by pressing the left and right mouse buttons at the same time. Alternatively, the pause button could be mapped to that. 

I understand this is a very specific scenario; if this isn't accepted, I will likely create a fork and attempt to add these myself. But I'm suggesting it here first, because A: I'm curious if anyone else happens to want this, and B: I'm not great with Javascript.

**Comment by vbguyny** [comment]
@IoIxDBu![Screenshot 2021-04-19 093145](https://user-images.githubusercontent.com/871502/115244677-29474b00-a0f2-11eb-98bb-1206b0a4f414.png)Stronger that sounds like a strange issue as you can use just a mouse (or finger on a mobile device) to use the site.  As mentioned in a pervious post (https://github.com/vbguyny/ws4kp/issues/50#issuecomment-799013467) I don't have a Raspberry Pi to test so I cannot quite understand what your issue.
When you are going into full screen mode are you able to see the black bars to the left/right of the WeatherStar 4000+ content? See ![Screenshot 2021-04-19 093145](https://user-images.githubusercontent.com/871502/115244677-29474b00-a0f2-11eb-98bb-1206b0a4f414.png)
Is there a way that you can make a recording that demonstrates the issue?

**Comment by IoIxDButStronger** [comment]
Here is a video showing the issue.
https://www.youtube.com/watch?v=jaq2wZVu-PY

**Comment by vbguyny** [comment]
@IoIxDButStronger thanks for that video!  Please visit the site and check how it looks on the CRT now :)

**Comment by IoIxDButStronger** [comment]
That was a better solution too! Thank you!

**Comment by IoIxDButStronger** [comment]
https://youtube.com/shorts/WRj3vvXoVnM?feature=share

**Comment by IoIxDButStronger** [comment]
Hi, it suddenly has gone back to how it was before, without me changing much of anything. Did you change the code, somehow?

**Comment by vbguyny** [comment]
Hello @IoIxDButStronger the last time the site has been updated was 19 days ago and had nothing that would affect this.

**Comment by IoIxDButStronger** [comment]
Again, late response, but if this is the case then would you consider just adding a toggle button to allow for the over-content menu as opposed to the under-content menu?

**Comment by vbguyny** [comment]
The logic for under-content menu has been disabled when in full screen mode.  It is now always over-content regardless of the screen orientation.
