### ISSUE TITLE
Regional Maps icons

### ISSUE THREAD

**Issue by malekmasoud** [vbguyny/ws4kp#52]
Here I come with more possible new icons for the regional conditions/forecast maps!

Partly Cloudy and Windy
![Partly Cloudy and Windy Day](https://user-images.githubusercontent.com/25880200/115862620-57829e80-a402-11eb-84fe-cf6b527f1f6f.gif)
![Partly Cloudy and Windy Night](https://user-images.githubusercontent.com/25880200/115862622-581b3500-a402-11eb-9284-d113dbcfaf01.gif)

Mostly Cloudy and Windy
![Mostly Cloudy and Windy Day](https://user-images.githubusercontent.com/25880200/115862531-42a60b00-a402-11eb-9cec-edfccaa085a3.gif)
![Mostly Cloudy and Windy Night](https://user-images.githubusercontent.com/25880200/115862536-433ea180-a402-11eb-9547-1a33e07b05e0.gif)

Cold
![Cold](https://user-images.githubusercontent.com/25880200/115862653-6406f700-a402-11eb-94c4-ff73baaf935e.gif)

Haze
![Haze](https://user-images.githubusercontent.com/25880200/115862694-71bc7c80-a402-11eb-8631-b8b1c6528497.gif)

Hot
![Hot](https://user-images.githubusercontent.com/25880200/115862708-75e89a00-a402-11eb-8a29-bc6b1f955336.gif)

Smoke
![Smoke](https://user-images.githubusercontent.com/25880200/115862754-826cf280-a402-11eb-97c7-b7b2319955fd.gif)

**Comment by vbguyny** [comment]
@malekmasoud these are awesome!  Thanks :D

**Comment by vbguyny** [comment]
Ok, they are now implemented in version 1.60
https://github.com/vbguyny/ws4kp/commit/b1fb952e8cc3971c57cd9e8998756bc9753b9489

**Comment by vbguyny** [comment]
![Screenshot_20210429-210540](https://user-images.githubusercontent.com/871502/116636282-f4779700-a92e-11eb-939c-c7147f204328.png)

**Comment by malekmasoud** [comment]
Hold it! I just wanted to add in more icons, this time with the following conditions:

Fair/Mostly Sunny (day)/Mostly Clear (night)
![FairDay-MostlySunny](https://user-images.githubusercontent.com/25880200/116767573-09236000-a9ff-11eb-9a92-915eb03d694a.gif)
![FairNight-MostlyClear](https://user-images.githubusercontent.com/25880200/116767572-088ac980-a9ff-11eb-84c5-5806009b92bb.gif)

Fair and Windy/Mostly Sunny and Windy (day)/Mostly Clear and Windy (night)
![Fair and Windy Day or Mostly Sunny and Windy](https://user-images.githubusercontent.com/25880200/116768064-00805900-aa02-11eb-9f95-f2e87d23f7d0.gif)
![Fair and Windy Night or Mostly Clear and Windy](https://user-images.githubusercontent.com/25880200/116768065-0118ef80-aa02-11eb-82aa-75c6f40c19f9.gif)

Cloudy and Windy
![Cloudy-Wind](https://user-images.githubusercontent.com/25880200/116767293-42f36700-a9fd-11eb-8754-6fdeee622365.gif)

Scattered Rain and/or Rain Squalls
![Scattered Rain or Rain Squalls Day](https://user-images.githubusercontent.com/25880200/116768085-1f7eeb00-aa02-11eb-838e-d0a0e81f50fb.gif)
![Scattered Rain or Rain Squalls Night](https://user-images.githubusercontent.com/25880200/116768083-1ee65480-aa02-11eb-8f23-2cb1725cf5d4.gif)

Scattered Snow and/or Snow Squalls
![Scattered Snow or Snow Squalls Day](https://user-images.githubusercontent.com/25880200/116768092-2b6aad00-aa02-11eb-9b05-1292f5213cb8.gif)
![Scattered Snow or Snow Squalls Night](https://user-images.githubusercontent.com/25880200/116768096-2f96ca80-aa02-11eb-86d3-a0a0c86fb08f.gif)

Isolated Thunderstorms
![Isolated Thunderstorms Day](https://user-images.githubusercontent.com/25880200/116767361-ba28fb00-a9fd-11eb-876b-6357731d8b53.gif)
![Isolated Thunderstorms Night](https://user-images.githubusercontent.com/25880200/116767360-ba28fb00-a9fd-11eb-8c6a-52fa0cb22e68.gif)

-

Also, here are a couple of icons for the Current Conditions and Extended Forecast screens

Fair/Mostly Sunny (day)/Mostly Clear (night)
![Fair Day-Mostly Sunny](https://user-images.githubusercontent.com/25880200/116768037-d9298c00-aa01-11eb-8893-650adea3335b.gif)
![Fair Night-Mostly Clear](https://user-images.githubusercontent.com/25880200/116768038-d9c22280-aa01-11eb-84df-b66b631c8fd1.gif)

**Comment by vbguyny** [comment]
Haha! Thanks for the icons! I'll try to add them at some point next week.

**Comment by malekmasoud** [comment]
I've decided to add in these two icons for the Extended Forecast screens into the pool for next week's icon update

Scattered Rain and/or Rain Squalls
![Scattered-Rain](https://user-images.githubusercontent.com/25880200/116799499-de510e80-aac7-11eb-8e19-cfc850e1f444.gif)

Scattered Snow and/or Snow Squalls
![Scattered-Snow](https://user-images.githubusercontent.com/25880200/116799500-dee9a500-aac7-11eb-8fae-5f2513a78135.gif)

**Comment by vbguyny** [comment]
Added new icons here: https://github.com/vbguyny/ws4kp/commit/9e6a515312836633d2779dc99aed3f184b3f162e
Some were duplicates
