### ISSUE TITLE
Allow raw video mode for CRTs

### ISSUE THREAD

**Issue by GenPDP7** [vbguyny/ws4kp#54]
Suggestion: give users the option to remove smoothing filters and display the raw (pixellated) video image for use on analog CRTs.

**Comment by vbguyny** [comment]
The smooth looks like a by-product of the browser's rendering engines and how they implement the canvas.  There is some limited success that for the radar data but I am not able to do this with fonts and other gradients.  That being said, it looks pretty good on a CRT.  See here: https://www.youtube.com/watch?v=WRj3vvXoVnM
