### ISSUE TITLE
Issue with the navigation buttons in full screen not disappearing after auto refresh.

### ISSUE THREAD

**Issue by vbguyny** [vbguyny/ws4kp#55]
Noticed that if you leave the site in full screen mode and it auto refreshes, the navigation buttons never disappear until you tap on the screen/move the mouse.

**Comment by lordvolvo** [comment]
/ws4kp/manifest.json?v=61:1 Failed to load resource: the server responded with a status of 404 (Not Found)

/ws4kp/manifest.json?v=61:1 Manifest: Line: 1, column: 1, Syntax error.

geocode.arcgis.com/a…9&_=1620951183223:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

index.js?v=61:347 Unable to unlock screen orientation.

/ws4kp/manifest.json?v=61:1 Failed to load resource: the server responded with a status of 404 (Not Found)

index.js?v=61:347 Unable to unlock screen orientation.

**Comment by vbguyny** [comment]
Ok try this:
Open chrome and go to https://geocode.arcgis.com/
Then go back to the the weather site and refresh the page and see if it still doesn't work

**Comment by lordvolvo** [comment]
That worked, thanks. I noticed on your server that you're running v. 1.63.  Should I download that?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 5/13/21  11:01 PM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Comment ***@***.***> Subject: Re: [vbguyny/ws4kp] Issue with the navigation buttons in full screen
  not disappearing after auto refresh. (#55) 
Ok try this:
Open chrome and go to https://geocode.arcgis.com/
Then go back to the the weather site and refresh the page and see if it still doesn't work

**Comment by vbguyny** [comment]
@lordvolvo Great!  It sounds like the SSL certificate for that site got removed when you cleared your browser cache data.
As for getting v1.63, is it a good idea to get the latest version as it contains new features and bug fixes.
