### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by lordvolvo** [vbguyny/ws4kp#59]
I'm having issues with the program freezing either on the loading screen or on the Current Conditions page.  I'm running Win 7 and Opera browser, although I've had this issue also on Chrome.  I clean the cache, close and open the browser, and even restart the PC.  The longest it goes without freezing is about two days.  I'm running v. 1.63.

Any help would be appreciated.  Thx!

**Comment by vbguyny** [comment]
Hello @lordvolvo working on my end for my location. What location are you using? I suspect an issue with NOAA.

**Comment by lordvolvo** [comment]
45529, Dayton Ohio.  Do you think the problem is data retrieval with the Wilmington Ohio office?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 6/19/21  9:42 AM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Mention ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing (#59) 
Hello @lordvolvo working on my end for my location. What location are you using? I suspect an issue with NOAA.

**Comment by vbguyny** [comment]
I don't see any issues at the moment. Sometimes NOAA does maintenance late at night which can cause issues with the site.

This is what I recommend you do:
1. Use the latest version of the site (1.64)
2. The next time this issue happens use the browser's inspector and copy any errors in the console.
3. Create a ticket here with the errors attached to the ticket.

**Comment by lordvolvo** [comment]
Just to let you know that I may have found a workaround to my freezing issues.  I changed the ZIP code the software access data for to one that is nearby and it's freezing much less now.  It's been a solid 5 days and I haven't had to manually refresh the browser.  Looks like you were right in saying that the NWS may have issues in sending data for a certain region.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 6/20/21  12:18 AM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Mention ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing (#59) 
I don't see any issues at the moment. Sometimes NOAA does maintenance late at night which can cause issues with the site.
This is what I recommend you do:

Use the latest version of the site (1.64)
The next time this issue happens use the browser's inspector and copy any errors in the console.
Create a ticket here with the errors attached to the ticket.

**Comment by vbguyny** [comment]
@lordvolvo I'm glad to hear! Could you explain what you did in a little more detail in case someone else has the same issue?

**Comment by lordvolvo** [comment]
When starting the program, I changed the zip code I normally used to a nearby zip code.  The one I had previously selected was freezing during the loading data screen.  Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 6/28/21  11:27 PM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Mention ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing (#59) 
@lordvolvo I'm glad to hear! Could you explain what you did in a little more detail in case someone else has the same issue?
