### ISSUE TITLE
NWWS or EMWIN backend?

### ISSUE THREAD

**Issue by egftechman** [vbguyny/ws4kp#61]
I'm looking at possibly forking this project and doing a DB based backend (either Postgres or CouchDB, deciding if relational store or document store makes more sense) populated using "PUSH" feeds like NWWS ( https://www.weather.gov/nwws/ ) XMPP feed or EMWIN ( https://www.weather.gov/emwin/ ) FTP feed, possibly be able to do a NOAAPORT satellite feed in the future also, so all requests from browsers are handled from local DB instead of proxying numerous requests to third party on demand services.  I've got some rudimentary ingest engines for working for both NWWS-OI (XMPP) and EMWIN (FTP) right now. 

Also looking at background data updating instead of having the update screen (i.e. have the screen/section check for update right after it is displayed for next round) .

I mention this as general discussion item. If someone else is working on such already, please respond so there aren't as many duplicated efforts.

**Comment by vbguyny** [comment]
Cool! 
Do you know where this is going to be hosted?

**Comment by egftechman** [comment]
It would just be a series of scripts one could run on a VPS or other server, either node.js or php based..I need to draw it out a bit (and really work on the parsers for the NWS products) and see how easily WS4000+ could integrate. If I don't base it on WS4000+, I have an alternate idea for an Openlayers based weather graphics system loosely inspired on the traditional weather channel systems.

**Comment by vbguyny** [comment]
It is possible to replace the URLs the site is currently pointing to which are currently being used to grab data to instead point to your backend. But there would need a lot of endpoints and in various formats (JSON, XML, custom text, binary blobs, etc.). It would be no small undertaking.
