### ISSUE TITLE
Marine Forecast segment not working?

### ISSUE THREAD

**Issue by Navi7002** [vbguyny/ws4kp#65]
When the marine forecast comes up, it just says "undefined" next to the winds and seas. I noticed that the marine forecast segment does work in towns near the ocean, but I don't live close enough to the ocean for it to work. Is there any possible way you could make it so that in towns that don't have an available marine forecast, the segment doesn't show up at all and go straight from the local forecast to the extended forecast? Thanks.

**Comment by vbguyny** [comment]
@Navi7002 the issue has been fixed in version 1.66 which is now live: https://battaglia.ddns.net/twc/
