### ISSUE TITLE
(Addition) Add original beeping noise when there is hazardous weather.

### ISSUE THREAD

**Issue by Jaydem808** [vbguyny/ws4kp#66]
I'd really like the same frequency used from the original.

**Comment by vbguyny** [comment]
@Jaydem808 is there an audio or video of this sounds on the internet some where?

**Comment by Jaydem808** [comment]
Also, here is another addition, and the source for the sound.  Is it alright if you add Air Quality back?
Air quality image showcase from 4 years ago: (https://user-images.githubusercontent.com/91167466/140232173-d8c27acb-ff5b-4b8f-ae7c-dedbfdcd0193.png)
Alert Frequency Sound is from 0:35 to 0:40: https://www.youtube.com/watch?v=fG206BR2lfg

**Comment by Jaydem808** [comment]
> @Jaydem808 is there an audio or video of this sounds on the internet some where?

I am also pretty sure you can extract it from Taiganet's simulator as well.

**Comment by vbguyny** [comment]
@Jaydem808 thanks. I didn't realize that the air quality wasn't working. What location are you using?

**Comment by vbguyny** [comment]
Btw I am not allowed to use any assets from Taiganet's Simulator. Been down that road 5 years ago...

**Comment by vbguyny** [comment]
It's working for me so it appears to be location based.  Here's a screenshot for Medford NY:
![Screenshot_20211104-075948](https://user-images.githubusercontent.com/871502/140310140-3ad8374c-33df-4501-97cb-2efd88b45863.png)

**Comment by vbguyny** [comment]
@Jaydem808 Beeping sound is now added in version 1.67
Note that it is only heard when you have the hazard text visible in the scroll area.

**Comment by Jaydem808** [comment]
Thanks! It isn't perfect, but alright!

**Comment by Jaydem808** [comment]
Whenever there is a weather emergency, can you try make current conditions cut to hazardous weather?

**Comment by vbguyny** [comment]
@Jaydem808 I received some feedback a while back where people didn't like it working that way.  You are more than welcome to fork the repo and make the changes yourself.
