### ISSUE TITLE
(Improvement) Perhaps you can make the WS4KP logo fit like the original TWC logo?

### ISSUE THREAD

**Issue by Jaydem808** [vbguyny/ws4kp#67]
The logo looks too small on the ui to me.

Also, my location is Hawaii.

**Comment by vbguyny** [comment]
@Jaydem808 the size of the logo will not be changed at this time. I highly recommend that you fork this repo and follow the instructions to make the modifications in a cloned version of the site: https://github.com/vbguyny/ws4kp/issues/18#issuecomment-512542620
