### ISSUE TITLE
Feature Request: Accept URL parameters to automatically set up the canvas.

### ISSUE THREAD

**Issue by IoIxD** [vbguyny/ws4kp#68]
I want to have this website be a widget on my Android phone since it'd go along with my theme, but you apparently can't have an actual web browser be a widget on Android. What you can instead have, is a widget that periodically takes a screenshot of a page and sets the widget to show it.

So I think it'd be nice to be able to set up the emulator with get parameters, so that I can have a widget that periodically screenshots the page and puts it on my home screen.

**Comment by vbguyny** [comment]
Hello @IoIxD 
If I understand you correctly, you want to have the site accept parameters as to get the weather?  If so there is already a parameter called "location" that you can set in the URL which will automatically get the weather for the location specified.
For example, https://battaglia.ddns.net/twc/?location=Orlando,%20FL will pull up the weather for Orlando, FL

**Comment by IoIxD** [comment]
Yes, that works, but I'd also like the ability to have it automatically go into fullscreen, and simply display a specific screen rather then wait for me to click the play button and listen to the music (which I can't even hear in a widget). 

What would essentially be ideal, is a url like `https://battaglia.ddns.net/twc/?fullscreen&screen=1&location=Orlando,%20FL`

**Comment by vbguyny** [comment]
As mentioned in a previous request, browsers do not allow sites to appear in full screen by default:
https://github.com/vbguyny/ws4kp/issues/50#issuecomment-815982339

**Comment by IoIxD** [comment]
Doesn't have to be proper fullscreen, it could also just be an option that removes the ui and makes the canvas element take up the whole screen.

That said, the canvas isn't the problem anyways. The page just doesn't load fast enough before the widget takes a screenshot of the page. I think I'm gonna have to set up a Browservice instance; I could somehow code a dedicated widget too but Browservice is likely easier.

**Comment by IoIxD** [comment]
In fact I'll open up a seperate issue on "fake fullscreen" because there is another, seperate reason to add it.
