### ISSUE TITLE
Incorrect panning

### ISSUE THREAD

**Issue by TwoTailedNeppy** [vbguyny/ws4kp#71]
the song Trammel Starks - Under The Influence is, for some reason, completely panned to the left ear and should probably be resubmitted as a regular mono audio file as out of all the minor annoyances that is a bit more of a bothering issue than a few songs being cd audio quality compared to the off the air quality recordings

**Comment by vbguyny** [comment]
@TwoTailedNeppy it most have always been like that.  I don't have the time or know how to fix this right now. If you can upload a fixed audio file I will replace the one on the site.

**Comment by vbguyny** [comment]
@RyanAaronGreen thanks again for helping out with this!
@TwoTailedNeppy the website has been updated with the patched audio file.
