### ISSUE TITLE
TWC  narrations (taken from VHS recordings - not Taiganet)

### ISSUE THREAD

**Issue by mdscott19** [vbguyny/ws4kp#72]
A clever individual (not me) was able to use audiostrip.co.uk to capture the Dan Chandler narrations from VHS recordings of The Weather Channel, making the resulting mp3's publicly available via Google Drive:

https://drive.google.com/drive/folders/1GPGgcSUGfcKwK85TuMFAhNdMahcYtP7H

Is there any possibility these could be used as an optional replacement for the browser-based narration?

**Comment by vbguyny** [comment]
@mdscott19 Cool! However I cannot remove the browser based narration for accessablity reasons.  You can always fork the repo and make your own version with Dan Chandler's voice!
