### ISSUE TITLE
OBS Studio has issues displaying the site

### ISSUE THREAD

**Issue by InterplexSoftworks** [vbguyny/ws4kp#74]
It glitches and always thinks its in full-screen mode. Full-screen mode also doesn't work.
![image](https://user-images.githubusercontent.com/95003670/175831445-d2aa4d72-b523-4a4b-ac26-0f3ddb4a9c6e.png)

**Comment by vbguyny** [comment]
Hello @InterplexSoftworks 
This sounds either like an issue with the browser or OBS. I know that you can capture the video as other people have done it recently: https://youtu.be/XifE4p8uBuc
