### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by Weatherstarfan** [vbguyny/ws4kp#75]
Everytime I open it the music doesn't start playing and I don't like it when it's silent because it makes me feel anxious.

**Comment by vbguyny** [comment]
Hello @Weatherstarfan sorry to hear about your issue.  Could you please provide me with the device, is and version, and which browser that you are using that you are experiencing this?

**Comment by Weatherstarfan** [comment]
Windows 8 is the computer
Opera GX is the browser

**Comment by vbguyny** [comment]
I don't have that browser.  I know that it works for Windows on Edge and Chrome.  Please try one of those browsers and try again.

**Comment by vbguyny** [comment]
Ok I am now able to see the issue. Not sure if it related to a recent update to chromium based browsers or my site.  

The following might be a work around:

By default, Chrome, Chromium Edge, and Firefox do not enable automatically playing audio and video files. The WebAudio.Play and WebVideo.Play steps may be successfully run but actual operations are not performed.

To enable running the WebAudio.Play and WebVideo.Play methods:

Configure the browser to allow autoplaying of audio and video files. Try the following options or check online for the relevant browser settings:

Chrome: Add a registry key called AutoplayAllowed to the Windows registry:

Location: HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome

Value: 0x00000001

Chromium Edge: In the Media autoplay settings of the browser, set Control if audio and video play automatically on sites to Allow.

Firefox: In the Autoplay settings of the browser, select Allow Audio and Video from the Default for all websites drop-down.

**Comment by vbguyny** [comment]
Appears to be related to a fix that was added to Chromium: https://developer.chrome.com/blog/autoplay/#webaudio

**Comment by vbguyny** [comment]
@Weatherstarfan ok, so here is the deal:

At some point in the last few years, there has been an update to Chromium based browsers (which includes Opera) that will only allow media to be played once the user has interacted with the page in some way (example, clicking on a button).  There is no way that I can work around this on my end.  However, adding the value to the Windows registry as indicated in the following link has worked for me:

https://admhelp.microfocus.com/uft/en/2021-2022/UFT_Help/Content/Addins_Guide/Chrome_Chromium_FF_Limitations.htm#:~:text=Internet%20Explorer%20only.-,Running%20the%20WebAudio.Play%20and%20WebVideo.Play%20methods,-By%20default%2C%20Chrome

Search for "Running the WebAudio.Play and WebVideo.Play methods"
