### ISSUE TITLE
No Icon for Lubbock Texas

### ISSUE THREAD

**Issue by Ethan8474** [vbguyny/ws4kp#76]

**Comment by vbguyny** [comment]
The city needs to be appended to the list of cities located here: https://github.com/vbguyny/ws4kp/blob/0de6423c65a91bf277222b73a04271b89aec8bcb/Scripts/RegionalCities.js
In addition to the name, the latitude and longitude has to be indicated

**Comment by Ethan8474** [comment]
I can't edit anything.

**Comment by vbguyny** [comment]
@Ethan8474 you need to fork this repo and make the fix on your machine.  Once you have made the change you can commit your changes and create a pull request.

**Comment by vbguyny** [comment]
Done, updated in v1.68 which is now live.
