### ISSUE TITLE
Cant get a number of things to work/update

### ISSUE THREAD

**Issue by Mattlennial** [vbguyny/ws4kp#77]
Just recently I noticed that the regional forecast/observations, hazardous weather, LDL and auto refresh are not working on their own. No music plays and the WeatherStar does not go to each slide automatically.
<img width="521" alt="rip" src="https://user-images.githubusercontent.com/114112012/191610318-091656a7-1db7-4404-9cd3-802c7b5f9b81.png">

**Comment by vbguyny** [comment]
@Mattlennial there is something strange going on where there is a City called "Indepedence 920" which is causing the site to error.  I added some additional validation and you should be able to pull up the weather now for Sarasota, FL.
