### ISSUE TITLE
Current Conditions not loading

### ISSUE THREAD

**Issue by realswamo** [vbguyny/ws4kp#78]
Hey there,

On your website, everything was working yesterday. Today, the Latest Observations is stuck at Loading, the music doesn't play and the current conditions scroll isn't loading, this is the error I got on the browser:

Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at WeatherCurrentConditions.<anonymous> (VM25 twc3.js:9998:41)
    at Function.each (VM10 jquery-3.1.0.min.js:2:2815)
    at r.fn.init.each (VM10 jquery-3.1.0.min.js:2:1003)
    at PopulateRegionalObservations.BackGroundImage.onload (VM25 twc3.js:9959:24)

![Capture](https://user-images.githubusercontent.com/33209961/193960800-a86367dd-fef0-4ad5-9c66-8cc132d12fa2.PNG)

Its an awesome website to have playing in the background. Please check it out if you have time, thanks!

**Comment by vbguyny** [comment]
@realswamo thanks for the compliment 😊
I'll try to take a look at the problem later today.

**Comment by vbguyny** [comment]
@realswamo The bug has been fixed in version 1.69 which is now live!
