### ISSUE TITLE
What is RSS feed for?

### ISSUE THREAD

**Issue by Ethan8474** [vbguyny/ws4kp#83]
What is RSS feed for?

**Comment by vbguyny** [comment]
Hello @Ethan8474,

The RSS option allows you to have the site display news headlines in the LDL (lower display line).  For example https://rss.slashdot.org/Slashdot/slashdotMain

Here is the original feature request: https://github.com/vbguyny/ws4kp/issues/15

**Comment by Ethan8474** [comment]
How do I make it say something?

**Comment by vbguyny** [comment]
If you want it to says something specific, select the option "Custom Text".  They enter the text and press the "Set" button.

**Comment by Ethan8474** [comment]
Ok cool! :D Thanks!!
