### ISSUE TITLE
Using geolocation api when there's a saved location

### ISSUE THREAD

**Issue by netbymatt** [vbguyny/ws4kp#85]
When I was working on a fork of this I noticed that when there's a saved location in local storage "TwcQuery" the code goes through the geolocation API twice, first for suggestions and then again to get the actual location number. It's kicked off by the ```blur(); focus()``` lines here.
https://github.com/vbguyny/ws4kp/blob/3e917051e0ff4c10e54440e0919847b8cab7c268/Scripts/index.js#L1394-L1400
There's a fairly simple way to avoid this by storing the lat/lon when it comes back from the API during the initial query. Then use the stored lat/lon to call ```doRedirectToGeometry()``` directly in the code highlighted above.

Would you like me to work on a pull request for this?

**Comment by vbguyny** [comment]
Hello @netbymatt !
Absolutely! I always appreciate the help from the community 😊
