### ISSUE TITLE
Local Radar not working

### ISSUE THREAD

**Issue by vbguyny** [vbguyny/ws4kp#88]
For the past few days the local radar has been unavailable.  The server reports "mesonet.agron.iastate.edu took too long to respond."

**Comment by akrherz** [comment]
The RADAR composite files are regular in-time and **should** always be there with a predictable cadence.  For example, if the current time is 1900 UTC, the 1900, 1855, 1850, 1845, etc files should all be there.  So the polling logic can simply be to rectify the current minute of the hour back to minute divisible by 5 and request that file from the server.

Additionally, this [JSON file](https://mesonet.agron.iastate.edu/data/gis/images/4326/USCOMP/n0q_0.json) exists which gives a timestamp of the most recent file that would be available from the archive.

I am happy to add whatever additional services you need to increase the efficiency of this.

**Comment by vbguyny** [comment]
Issue fixed in version 1.73 and the website has been patched.
