### ISSUE TITLE
Multiple Observations for Boulder Municipal Airport

### ISSUE THREAD

**Issue by kbooker79** [vbguyny/ws4kp#89]
![Screenshot 2023-03-03 at 1 13 15 PM](https://user-images.githubusercontent.com/25211554/222818960-85ce6254-855e-4c48-9216-5b64637af3b8.png)

Multiple references and subsequent observations to Boulder Municipal Airport are being displayed and only one is actually correct.

**Comment by vbguyny** [comment]
@kbooker79 could you please let know what location you entered in the site?

**Comment by kbooker79** [comment]
> @kbooker79 could you please let know what location you entered in the site?

Hi @vbguyny, in this case 80026 (Lafayette, Erie, CO).

**Comment by kbooker79** [comment]
This appears to be correct now...thank you
