### ISSUE TITLE
Add on screen entertainment segments

### ISSUE THREAD

**Issue by Sonic4Tails** [vbguyny/ws4kp#90]
basically what i mean is that on an original weatherstar 4000 the forecast was in between on screen entertainment so maybe add an option to enable or disable that and if its enabled either a user can add it to for example obs studio and then place an image on top or be able to set a video url

**Comment by Sonic4Tails** [comment]
yes but the video ticker had the date and time embedded aswell as it was the same one used as the NWS warning screen

**Comment by Sonic4Tails** [comment]
you can also just make the top part a greenscreen and then let the user be able to overlay an video on top

**Comment by vbguyny** [comment]
Hello @Sonic4Tails according to the following article all that you need to do is add an overlay that is playing the entertainment and then use the WeatherStar 4000+ has the background.
Refer to the following article for more information:
https://support.streamelements.com/en/articles/25-adding-an-overlay-to-obs-studio

**Comment by Sonic4Tails** [comment]
@vbguyny 
you would not have the added clock and date shown like with the alert segments
