### ISSUE TITLE
Future Sugestions

### ISSUE THREAD

**Issue by Ethan8474** [vbguyny/ws4kp#92]
Could you add live EAS scroll on the bottom and possibly add narration in there near future, I completely understand if you are busy or can't.

**Comment by vbguyny** [comment]
@Ethan8474 could you please elaborate what you mean by EAS? If it is something that has an RSS feed for it you can dump that into the site today.

**Comment by Ethan8474** [comment]
How would I be able to put an RSS feed on the site? Would I just put the RSS feed in the "RSS feed" section under "Scroll Options"?

**Comment by vbguyny** [comment]
Correct

**Comment by Ethan8474** [comment]
Cool! Do I have to disable Hazardous Weather or could it be on with the RSS feed?

**Comment by vbguyny** [comment]
You can use the Hazardous Weather with the RSS feed option. How it works is that the site will display the text from the RSS feed by default. But if there is a hazardous alert in effect, it will supercede the RSS feed and display the alert.
