### ISSUE TITLE
Radar 

### ISSUE THREAD

**Issue by stubbertville** [vbguyny/ws4kp#93]
Is there plans to fix the radar anytime soon?

**Comment by vbguyny** [comment]
@stubbertville appears to be working for me:
![Screenshot_20230513-222423](https://github.com/vbguyny/ws4kp/assets/871502/3b568eee-e643-4a3e-8d5f-0a2398ac17d2)

Could you please indicate your location that this is happening?

You might be thinking of the WeatherStar 4000 simulator.

**Comment by stubbertville** [comment]
Ooops I’m so sorry yeah I was my bad, does make me want to use this one for that feature lol, would I be able to run the site on a pi 1? And have it automatically boot to it

**Comment by vbguyny** [comment]
@stubbertville understandable 😄
Not sure about working on a Pi 1 but you are welcome to try!
The radar for the desktop simulator has been down since the end of 2019 and it doesn't look like it is going to be fixed anytime soon.

**Comment by stubbertville** [comment]
Well that sucks, I’ve been actually using it on one of my analog TV channels, I broadcasted on channel 46 in my house
