### ISSUE TITLE
Loading Screen Question

### ISSUE THREAD

**Issue by zonexero** [vbguyny/ws4kp#96]
Emulation is looking and work great, thanks for all the hard work!  I have an odd question/request....on the 'Loading' screen is there a way to change "Press Here" to something else like "Ready" or "Loaded".    Either that or maybe a way to hide the loading/re-loading screen?   Just curious.  Thanks!

One other smaller thing I noticed, if I type in Tampa, FL it has the Marine conditions, yet they are not loading when I type om nearby St. Petersburg or Clearwater, both those cities have far more water around them than Tampa, just seems strange.  My guess was the Marine conditions are maybe more reserved for the larger cities?

**Comment by vbguyny** [comment]
@zonexero 

Thanks for the compliant!

Regarding your first question, I have no plans on making a change to the loading screen at this time. However, you are welcome to fork this repo and make any changes you'd like :)

As far as the marine forecast is concerned, sometimes the forecast is either unavailable or not working for certain locations which is more of a NOAA issue than the WS4K+
