### ISSUE TITLE
Not all NWS Products posting

### ISSUE THREAD

**Issue by Weatherman436** [vbguyny/ws4kp#97]
I love the WeatherStar 4000+. I just wanted to report an issue I spotted with it. It's not receiving all of the alerts. Severe weather watches and warnings (like Severe Thunderstorm Watches and Severe Thunderstorm Warnings for example) are not showing up. Not sure why, but wanted to report it so it can be investigated.

**Comment by vbguyny** [comment]
@Weatherman436 - I'm glad you like it :)

I see that the severe weather is working (see attachment image from a minute ago). Keep in mind that some products work somewhat differently depending on which region you are querying. Also NOAA sometimes changes or brings down products for reasons which are not provided to me ahead of time.

![image](https://github.com/vbguyny/ws4kp/assets/871502/2e627066-1c9e-483e-a2fc-70c8a2209164)
