### ISSUE TITLE
Regional Observations no longer works

### ISSUE THREAD

**Issue by Crisukomie** [vbguyny/ws4kp#99]
Regional Observations says "loading" indefinitely which causes the entire thing to not not autoplay.

I don't know if this is related or not, but the music also doesn't work anymore.

**Comment by vbguyny** [comment]
@Crisukomie it appears to be working now. Please check again and if it still doesn't work please include the location that you are using.

Sometimes NOAA goes down for one reason or another and that causes the site to stop working. There isn't much I can do about that.

Yes, the music doesn't play when this happens.

**Comment by joeventura1** [comment]
I have the same issue with Hazardous Weather in a NO DATA state in Lancaster PA 17601 which also causes it not to autoplay

**Comment by Crisukomie** [comment]
> 
Just chiming in to let you know that it does appear to be fixed now. Thanks!

**Comment by joeventura1** [comment]
Still having the issue with Hazardous Weather in a NO DATA state in Lancaster PA 17601

**Comment by vbguyny** [comment]
Hazardous Weather having NO DATA is normal. The site should still load. I'll take a look.

**Comment by vbguyny** [comment]
@joeventura1 The auto-play works on my end using Chrome on Windows 11. Could you please indicate under what OS and browser you are running the site?

**Comment by joeventura1** [comment]
IE Edge on Win 10

I'll go upgrade to Chrome right now!

**Comment by vbguyny** [comment]
Awesome! Glad to hear that you got it working.
